// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → phrases1*
 */
export interface AboutDocumentDataPhrases1Item {
  /**
   * text1 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * text2 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * text3 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;
}

/**
 * Item in *About → phrases2*
 */
export interface AboutDocumentDataPhrases2Item {
  /**
   * text1 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * text2 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * text3 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;
}

type AboutDocumentDataSlicesSlice = ImageSlideSlice | About1Slice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title1 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * Text1 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * Image1 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Title2 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * Text2 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * Image2 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;

  /**
   * Image4 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * Title3 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title3: prismic.RichTextField;

  /**
   * Text3 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;

  /**
   * phrases1 field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  phrases1: prismic.GroupField<Simplify<AboutDocumentDataPhrases1Item>>;

  /**
   * phrases2 field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  phrases2: prismic.GroupField<Simplify<AboutDocumentDataPhrases2Item>>;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type AccountabilityDocumentDataSlicesSlice = DocumentSlice;

/**
 * Content for Accountability documents
 */
interface AccountabilityDocumentData {
  /**
   * Accountability Title field in *Accountability*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability.accountability_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accountability_title: prismic.KeyTextField;

  /**
   * Accountability Text field in *Accountability*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability.accountability_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accountability_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Accountability*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccountabilityDocumentDataSlicesSlice> /**
   * Meta Description field in *Accountability*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accountability.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accountability*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Accountability*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accountability.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Accountability document from Prismic
 *
 * - **API ID**: `accountability`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccountabilityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AccountabilityDocumentData>,
    "accountability",
    Lang
  >;

/**
 * Item in *Accountability_card → Anex*
 */
export interface AccountabilityCardDocumentDataAnexItem {
  /**
   * File field in *Accountability_card → Anex*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.anex[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField;

  /**
   * Title field in *Accountability_card → Anex*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.anex[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Content for Accountability_card documents
 */
interface AccountabilityCardDocumentData {
  /**
   * Text field in *Accountability_card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Title field in *Accountability_card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *Accountability_card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Ofício" | "Prestação de Contas">;

  /**
   * Anex field in *Accountability_card*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accountability_card.anex[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  anex: prismic.GroupField<Simplify<AccountabilityCardDocumentDataAnexItem>>;
}

/**
 * Accountability_card document from Prismic
 *
 * - **API ID**: `accountability_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccountabilityCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AccountabilityCardDocumentData>,
    "accountability_card",
    Lang
  >;

type CalendarDocumentDataSlicesSlice = EventCardSlice;

/**
 * Content for Calendar documents
 */
interface CalendarDocumentData {
  /**
   * calendar_tilte field in *Calendar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.calendar_tilte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  calendar_tilte: prismic.RichTextField;

  /**
   * calendar_subtitle field in *Calendar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.calendar_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  calendar_subtitle: prismic.RichTextField;

  /**
   * calendar_text field in *Calendar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.calendar_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  calendar_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Calendar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CalendarDocumentDataSlicesSlice> /**
   * Meta Description field in *Calendar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: calendar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Calendar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Calendar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: calendar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Calendar document from Prismic
 *
 * - **API ID**: `calendar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CalendarDocumentData>,
    "calendar",
    Lang
  >;

type ContactDocumentDataSlicesSlice = ContactCardSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * text 1 field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.text_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_1: prismic.KeyTextField;

  /**
   * text 2 field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.text_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_2: prismic.RichTextField;

  /**
   * Endereço field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.endereco
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  endereco: prismic.RichTextField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type EquipmentDocumentDataSlicesSlice = ImageSlideSlice;

/**
 * Content for Equipment documents
 */
interface EquipmentDocumentData {
  /**
   * Title field in *Equipment*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipment.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Equipment*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipment.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Read More field in *Equipment*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: equipment.read_more
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  read_more: prismic.LinkField;

  /**
   * Image field in *Equipment*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: equipment.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Equipment*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: equipment.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EquipmentDocumentDataSlicesSlice>;
}

/**
 * Equipment document from Prismic
 *
 * - **API ID**: `equipment`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EquipmentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EquipmentDocumentData>,
    "equipment",
    Lang
  >;

/**
 * Content for Events_card documents
 */
interface EventsCardDocumentData {
  /**
   * event_image field in *Events_card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events_card.event_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  event_image: prismic.ImageField<never>;

  /**
   * event_title field in *Events_card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_card.event_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_title: prismic.RichTextField;

  /**
   * event_text field in *Events_card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_card.event_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_text: prismic.RichTextField;

  /**
   * event_date field in *Events_card*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events_card.event_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  event_date: prismic.DateField;

  /**
   * register_link field in *Events_card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events_card.register_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  register_link: prismic.LinkField;
}

/**
 * Events_card document from Prismic
 *
 * - **API ID**: `events_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventsCardDocumentData>,
    "events_card",
    Lang
  >;

type HomeDocumentDataSlicesSlice = ImageSlideSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * home_title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.home_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  home_text: prismic.RichTextField;

  /**
   * home_subtitle field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.home_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  home_subtitle: prismic.RichTextField;

  /**
   * text_title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.text_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_title: prismic.RichTextField;

  /**
   * header_image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * about_image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  about_image: prismic.ImageField<never>;

  /**
   * about_title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_title: prismic.RichTextField;

  /**
   * about_text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_text: prismic.RichTextField;

  /**
   * title_core_1 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_core_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_core_1: prismic.RichTextField;

  /**
   * text_core_1 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.text_core_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_core_1: prismic.RichTextField;

  /**
   * title_core_2 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_core_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_core_2: prismic.RichTextField;

  /**
   * text_core_2 field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.text_core_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_core_2: prismic.RichTextField;

  /**
   * image_core_1 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.image_core_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_core_1: prismic.ImageField<never>;

  /**
   * image_core_2 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.image_core_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_core_2: prismic.ImageField<never>;

  /**
   * main_core_tile field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.main_core_tile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_core_tile: prismic.RichTextField;

  /**
   * main_core_text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.main_core_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_core_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type NewsDocumentDataSlicesSlice = never;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * main_news_image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.main_news_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_news_image: prismic.ImageField<never>;

  /**
   * main_news_title field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.main_news_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_news_title: prismic.RichTextField;

  /**
   * main_news_description field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.main_news_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_news_description: prismic.RichTextField;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cover field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * description field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Author Name field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do autor
   * - **API ID Path**: post.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cargo/Título do autor
   * - **API ID Path**: post.author_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_title: prismic.KeyTextField;

  /**
   * Author Photo field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.author_photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_photo: prismic.ImageField<never>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Item in *slideImage → title*
 */
export interface SlideimageDocumentDataTitleItem {}

/**
 * Content for slideImage documents
 */
interface SlideimageDocumentData {
  /**
   * image field in *slideImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slideimage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *slideImage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slideimage.title[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title: prismic.GroupField<Simplify<SlideimageDocumentDataTitleItem>>;
}

/**
 * slideImage document from Prismic
 *
 * - **API ID**: `slideimage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SlideimageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SlideimageDocumentData>,
    "slideimage",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | AccountabilityDocument
  | AccountabilityCardDocument
  | CalendarDocument
  | ContactDocument
  | EquipmentDocument
  | EventsCardDocument
  | HomeDocument
  | NewsDocument
  | PostDocument
  | SlideimageDocument;

/**
 * Default variation for About1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type About1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *About1*
 */
type About1SliceVariation = About1SliceDefault;

/**
 * About1 Shared Slice
 *
 * - **API ID**: `about1`
 * - **Description**: About1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type About1Slice = prismic.SharedSlice<"about1", About1SliceVariation>;

/**
 * Primary content in *ContactCard → Primary*
 */
export interface ContactCardSliceDefaultPrimary {
  /**
   * Icon field in *ContactCard → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: email
   * - **API ID Path**: contact_card.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"email" | "whats app" | "instagram", "filled">;

  /**
   * Title field in *ContactCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *ContactCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Link field in *ContactCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Button Text field in *ContactCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactCard*
 */
type ContactCardSliceVariation = ContactCardSliceDefault;

/**
 * ContactCard Shared Slice
 *
 * - **API ID**: `contact_card`
 * - **Description**: ContactCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCardSlice = prismic.SharedSlice<
  "contact_card",
  ContactCardSliceVariation
>;

/**
 * Primary content in *Document → Primary*
 */
export interface DocumentSliceDefaultPrimary {
  /**
   * Title field in *Document → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: document.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Document → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: document.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * type field in *Document → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Ofício
   * - **API ID Path**: document.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Ofício" | "Prestação de Contas", "filled">;
}

/**
 * Primary content in *Document → Items*
 */
export interface DocumentSliceDefaultItem {
  /**
   * Annex field in *Document → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: document.items[].annex
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  annex: prismic.LinkToMediaField;

  /**
   * Annex Title field in *Document → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: document.items[].annex_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  annex_title: prismic.KeyTextField;
}

/**
 * Default variation for Document Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DocumentSliceDefaultPrimary>,
  Simplify<DocumentSliceDefaultItem>
>;

/**
 * Slice variation for *Document*
 */
type DocumentSliceVariation = DocumentSliceDefault;

/**
 * Document Shared Slice
 *
 * - **API ID**: `document`
 * - **Description**: Document
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentSlice = prismic.SharedSlice<
  "document",
  DocumentSliceVariation
>;

/**
 * Primary content in *EventCard → Primary*
 */
export interface EventCardSliceDefaultPrimary {
  /**
   * event_image field in *EventCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.primary.event_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  event_image: prismic.ImageField<never>;

  /**
   * event_title field in *EventCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.primary.event_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_title: prismic.RichTextField;

  /**
   * event_text field in *EventCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.primary.event_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_text: prismic.RichTextField;

  /**
   * event_date field in *EventCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.primary.event_date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_date: prismic.RichTextField;
}

/**
 * Primary content in *EventCard → Items*
 */
export interface EventCardSliceDefaultItem {
  /**
   * event_image field in *EventCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.items[].event_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  event_image: prismic.ImageField<never>;
}

/**
 * Default variation for EventCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventCardSliceDefaultPrimary>,
  Simplify<EventCardSliceDefaultItem>
>;

/**
 * Slice variation for *EventCard*
 */
type EventCardSliceVariation = EventCardSliceDefault;

/**
 * EventCard Shared Slice
 *
 * - **API ID**: `event_card`
 * - **Description**: EventCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventCardSlice = prismic.SharedSlice<
  "event_card",
  EventCardSliceVariation
>;

/**
 * Primary content in *ImageSlide → Items*
 */
export interface ImageSlideSliceDefaultItem {
  /**
   * image field in *ImageSlide → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slide.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ImageSlide → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slide.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for ImageSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageSlideSliceDefaultItem>
>;

/**
 * Slice variation for *ImageSlide*
 */
type ImageSlideSliceVariation = ImageSlideSliceDefault;

/**
 * ImageSlide Shared Slice
 *
 * - **API ID**: `image_slide`
 * - **Description**: ImageSlide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideSlice = prismic.SharedSlice<
  "image_slide",
  ImageSlideSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataPhrases1Item,
      AboutDocumentDataPhrases2Item,
      AboutDocumentDataSlicesSlice,
      AccountabilityDocument,
      AccountabilityDocumentData,
      AccountabilityDocumentDataSlicesSlice,
      AccountabilityCardDocument,
      AccountabilityCardDocumentData,
      AccountabilityCardDocumentDataAnexItem,
      CalendarDocument,
      CalendarDocumentData,
      CalendarDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      EquipmentDocument,
      EquipmentDocumentData,
      EquipmentDocumentDataSlicesSlice,
      EventsCardDocument,
      EventsCardDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      SlideimageDocument,
      SlideimageDocumentData,
      SlideimageDocumentDataTitleItem,
      AllDocumentTypes,
      About1Slice,
      About1SliceVariation,
      About1SliceDefault,
      ContactCardSlice,
      ContactCardSliceDefaultPrimary,
      ContactCardSliceVariation,
      ContactCardSliceDefault,
      DocumentSlice,
      DocumentSliceDefaultPrimary,
      DocumentSliceDefaultItem,
      DocumentSliceVariation,
      DocumentSliceDefault,
      EventCardSlice,
      EventCardSliceDefaultPrimary,
      EventCardSliceDefaultItem,
      EventCardSliceVariation,
      EventCardSliceDefault,
      ImageSlideSlice,
      ImageSlideSliceDefaultItem,
      ImageSlideSliceVariation,
      ImageSlideSliceDefault,
    };
  }
}
